name: Trigger KernelSU Build

on:
  workflow_dispatch:  # 手动按钮触发

jobs:
  build:
    uses: WildPlusKernel/OnePlus_KernelSU_SUSFS/.github/workflows/build.yml@main
    with:
      model: salami
      soc: sm8550
      branch: oneplus/sm8550
      manifest: default.xml
      android_version: "android14"
      kernel_version: "5.15"
